# Configuracion para Hyprland Autoname Workspaces
# https://github.com/mxhectorvega/hyprland
# Version: v1.0 01/04/2023

# Añade tu asignación de iconos
# use comillas dobles la clave y el valor
# Tome el nombre de cada una las ventanas 
# abiertas con 'hyprctl clients | grep class'

[icons]

"DEFAULT" = ""
"gnome-terminal-server" = ""
"foot" = ""
"kitty" = ""
"Firefox" = ""
"Microsoft-edge" = ""
"org.pwmt.zathura" = ""
"evince" = ""
"org.gnome.Nautilus" = ""
"thunar" = ""
"Spotify" = ""
"Gimp-2.10" = ""
"libreoffice-writer" = ""
"libreoffice-calc" = ""
"libreoffice-impress" = ""
"org.telegram.desktop" = ""
"org.gnome.TextEditor" = ""
"xdg-desktop-portal-gnome" = ""
"YouTube" = ""
"virt-manager" = ""
"eog" = ""
"com.obsproject.Studio" = ""
"Steam" = ""
"Whatsapp" = ""
"Twitter" = ""
"Tiktok" = ""
"Instagram" = ""
"Facebook" = ""
"VSCodium" = ""
"pamac-manager" = ""
"Steam" = ""
"mcpelauncher-client" = ""
"Imagen en Imagen" = ""
"Netflix" = ""

#                             

# Agregue sus aplicaciones que necesitan ser excluidas
# La clave es la clase, el valor es el título.
# Puede poner un título vacío para excluir en función de
# solo nombre de clase 'nombre del software'

[exclude]
wofi = "*"
