#!/usr/bin/env bash

link=$(curl -s "https://es.wttr.in/$1?format=%l:+%c+%C+%t+%w\n")
icono=$(echo "$link" | awk '{print $2}')
condicion=$(echo "$link" | awk '{print $3, $4}')
temperatura=$(echo "$link" | awk '{print $5, $6}')
completo=$(echo "$link")

echo "{\"text\":\"$temperatura\n$condicion\", \"alt\":\"$icono\", \"tooltip\":\"$completo\"}"
