#!/usr/bin/env bash

link1=$(curl -s "https://es.wttr.in/$1?format=%l+%c+%C+%t+%w\n")
link2=$(curl -s "https://es.wttr.in/$1?format=%C")
link3=$(curl -s "https://es.wttr.in/$1?format=%t+%w")
link4=$(curl -s "https://es.wttr.in/$1?format=%c")

completo=$(echo "$link1")
condicion=$(echo "$link2")
temperatura=$(echo "$link3")
icono=$(echo "$link4")

echo "{\"text\":\"$temperatura\n$condicion\", \"alt\":\"$icono\", \"tooltip\":\"$completo\"}"
