#!/bin/bash

rm -rf $HOME/.config/wofi/style.css
rm -rf $HOME/.config/waybar/windows_style/style.css
rm -rf $HOME/.config/mako/config

cp $HOME/.config/wofi/temas/claro.css $HOME/.config/wofi/style.css
cp $HOME/.config/waybar/windows_style/temas/claro.css $HOME/.config/waybar/windows_style/style.css
cp $HOME/.config/mako/temas/windows_style/claro $HOME/.config/mako/config

sed -i "s/obscuro/claro/g" $HOME/.config/kitty/kitty.conf
sed -i "s/gris/claro/g" $HOME/.config/kitty/kitty.conf
sed -i "s/background_opacity       0.90/background_opacity       0.80/g" $HOME/.config/kitty/kitty.conf

sed -i "s/color=0f0f0f dddddd/color=ffffff 505050/g" $HOME/.config/foot/foot.ini
sed -i "s/foreground=dddddd/foreground=505050/g" $HOME/.config/foot/foot.ini
sed -i "s/background=0f0f0f/background=ffffff/g" $HOME/.config/foot/foot.ini
sed -i "s/background=242424/background=ffffff/g" $HOME/.config/foot/foot.ini
sed -i "s/alpha=0.90/alpha=0.80/g" $HOME/.config/foot/foot.ini

sed -i "s/windowrule=opacity 0.90/windowrule=opacity 0.85/g" $HOME/.config/hypr/hyprland.conf

rm -rf ${HOME}/.config/gtk-*

#cp -R $HOME/.themes/Colloid-Light/gtk-* ${HOME}/.config
#cp -R $HOME/.themes/Colloid-Light/gtk-2* ${HOME}/.config
#cp -R $HOME/.themes/Colloid-Light/gtk-3* ${HOME}/.config
cp -R $HOME/.themes/Colloid-Light/gtk-4* ${HOME}/.config

gsettings set org.gnome.desktop.interface gtk-theme 'Colloid-Light'
gsettings set org.gnome.desktop.interface icon-theme "Colloid-light"
gsettings set org.gnome.desktop.interface font-name 'SF Compact Display SemiBold 9'
gsettings set org.gnome.desktop.interface monospace-font-name 'SF Mono 10'
gsettings set org.gnome.desktop.interface document-font-name 'SF Compact Display SemiBold 9'
gsettings set org.gnome.desktop.wm.preferences titlebar-font 'SF Compact Display SemiBold 9'
gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"
gsettings set org.gnome.desktop.default-applications.terminal exec 'foot'

pkill -9 mako
mako &
pkill -9 waybar
waybar --config=$HOME/.config/waybar/windows_style/config --style=$HOME/.config/waybar/windows_style/style.css &
sleep 0.5
notify-send --expire-time 3000 --icon $HOME/.config/mako/hypr.ico 'Tema claro' 'La configuración se aplico satisfactoriamente'
swaybg -i $HOME/.config/wall/claro.*


