#! /usr/bin/env bash

pkill -9 wofi

chmod +x $HOME/.config/waybar/yabai_style/scripts/power-menu

show_menu() {
     bloquear="		Bloquear"
    suspender="		Suspender"
    reiniciar="		Reiniciar"
     hibernar="	Hibernar"
       apagar="		Apagar"
       cerrar="	Cerrar sesión"

    opciones="$bloquear\n$cerrar\n$reiniciar\n$apagar\n$suspender\n$hibernar"

    seleccionar="$(echo -e "$opciones" | $wofi)"

    case $seleccionar in
        "" | $divider)
            echo "Opción no seleccionada"
            ;;
        $bloquear)
            swaylock
            ;;
        $suspender)
            $($bloquear) && sleep 1; systemctl suspend
            ;;
        $cerrar)
            loginctl terminate-session $XDG_SESSION_ID
            ;;
        $reiniciar)
            systemctl reboot
            ;;
        $apagar)
            systemctl poweroff
            ;;
        $hibernar)
            $($bloquear) && sleep 1; systemctl hibernate
            ;;
        *)
            uptime
            ;;
    esac
}

show_icon() {
    echo "Loco"
}

wofi="wofi -p Selecciona... --no-actions --allow-images --show dmenu -n -i -I -W 250 -H 320"

case "$1" in
    --show)
        show_icon
        ;;
    *)
        show_menu
        ;;
esac
