#!/bin/bash

loco=$(printf "Bloquear\nCerrar sesion\nApagar\nReiniciar\nSuspender\nHibernar\nSuspencion hibrida\nSuspender y luego hibernar" | wofi \
      --dmenu \
      --width 250 \
      --lines 8 \
      --prompt Powermenu)

if [[ $loco = "Bloquear" ]]; then
	hyprctl dispatch dpms off
	exec lockscreen
elif [[ $loco = "Cerrar sesión" ]]; then
	kill -9 -1
elif [[ $loco = "Apagar" ]]; then
	systemctl poweroff
elif [[ $loco = "Reiniciar" ]]; then
	systemctl reboot
elif [[ $loco = "Suspender" ]]; then
	systemctl suspend
elif [[ $loco = "Hibernar" ]]; then
	systemctl hibernate
elif [[ $loco = "Suspensión híbrida" ]]; then
	systemctl hybrid-sleep
elif [[ $loco = "Suspender y luego hibernar" ]]; then
	systemctl suspend-then-hibernate
fi
