#!/bin/bash

rm -rf $HOME/.config/waybar/style.css
rm -rf $HOME/.config/wofi/style.css
rm -rf $HOME/.config/mako/config

cp $HOME/.config/wofi/temas/obscuro.css $HOME/.config/wofi/style.css
cp $HOME/.config/waybar/temas/obscuro.css $HOME/.config/waybar/style.css
cp $HOME/.config/mako/temas/obscuro $HOME/.config/mako/config

#sed -i "s/claro/obscuro/g" $HOME/.config/kitty/kitty.conf
#sed -i "s/gris/obscuro/g" $HOME/.config/kitty/kitty.conf

#sed -i "s/color=ffffff 505050/color=000000 dddddd/g" $HOME/.config/foot/foot.ini
#sed -i "s/foreground=505050/foreground=dddddd/g" $HOME/.config/foot/foot.ini
#sed -i "s/background=ffffff/background=000000/g" $HOME/.config/foot/foot.ini
#sed -i "s/background=242424/background=000000/g" $HOME/.config/foot/foot.ini

rm -rf ${HOME}/.config/gtk-*

cp -R $HOME/.themes/Colloid-Dark/gtk-* ${HOME}/.config

pkill -9 mako
mako &
pkill -9 waybar
waybar &
sleep 0.5
notify-send --expire-time 3000 --icon $HOME/.config/mako/hypr.ico 'Tema obscuro' 'La configuracion se aplico satisfactoriamente'
swaybg -i $HOME/.config/wall/obscuro.*

