#!/bin/bash

notify-send --expire-time 10000 --icon $HOME/.config/mako/hypr.ico 'Cambiado a modo claro' 'La configuracion se aplicara en unos segundos...'
sleep 0.5

rm -rf $HOME/.config/waybar/style.css
rm -rf $HOME/.config/wofi/style.css
rm -rf $HOME/.config/mako/config

cp $HOME/.config/wofi/temas/claro.css $HOME/.config/wofi/style.css
cp $HOME/.config/waybar/temas/claro.css $HOME/.config/waybar/style.css
cp $HOME/.config/mako/temas/claro $HOME/.config/mako/config

#sed -i "s/obscuro/claro/g" $HOME/.config/kitty/kitty.conf
#sed -i "s/gris/claro/g" $HOME/.config/kitty/kitty.conf

#sed -i "s/color=000000 dddddd/color=ffffff 505050/g" $HOME/.config/foot/foot.ini
#sed -i "s/foreground=dddddd/foreground=505050/g" $HOME/.config/foot/foot.ini
#sed -i "s/background=000000/background=ffffff/g" $HOME/.config/foot/foot.ini
#sed -i "s/background=242424/background=ffffff/g" $HOME/.config/foot/foot.ini

rm -rf ${HOME}/.config/gtk-2.0
rm -rf ${HOME}/.config/gtk-3.0
rm -rf ${HOME}/.config/gtk-4.0

cp -R $HOME/.themes/Colloid-Light/gtk-2.0 ${HOME}/.config/gtk-2.0
cp -R $HOME/.themes/Colloid-Light/gtk-3.0 ${HOME}/.config/gtk-3.0
cp -R $HOME/.themes/Colloid-Light/gtk-4.0 ${HOME}/.config/gtk-4.0

pkill -9 mako
mako &
pkill -9 waybar
waybar &
swaybg -i $HOME/.config/wall/claro.*
