#!/bin/bash

rm -rf $HOME/.config/waybar/style.css
rm -rf $HOME/.config/wofi/style.css
rm -rf $HOME/.config/mako/config

cp $HOME/.config/waybar/temas/claro.css $HOME/.config/waybar/style.css
cp $HOME/.config/wofi/temas/claro.css $HOME/.config/wofi/style.css
cp $HOME/.config/mako/temas/claro $HOME/.config/mako/config

#sed -i "s/obscuro/claro/g" $HOME/.config/kitty/kitty.conf
#sed -i "s/gris/claro/g" $HOME/.config/kitty/kitty.conf

#sed -i "s/color=000000 dddddd/color=ffffff 505050/g" $HOME/.config/foot/foot.ini
#sed -i "s/foreground=dddddd/foreground=505050/g" $HOME/.config/foot/foot.ini
#sed -i "s/background=000000/background=ffffff/g" $HOME/.config/foot/foot.ini
#sed -i "s/background=242424/background=ffffff/g" $HOME/.config/foot/foot.ini

rm -rf ${HOME}/.config/gtk-*

cp -R $HOME/.themes/Colloid-Light/gtk-* ${HOME}/.config

pkill -9 mako
mako &
pkill -9 waybar
waybar &
sleep 0.5
notify-send --expire-time 3000 --icon $HOME/.config/mako/hypr.ico 'Tema claro' 'La configuracion se aplico satisfactoriamente'
swaybg -i $HOME/.config/wall/claro.*

