#!/bin/bash

notify-send --expire-time 10000 --icon $HOME/.config/mako/hypr.ico 'Cambiado a modo obscuro' 'La configuracion se aplicara en unos segundos...'
sleep 0.5

rm -rf $HOME/.config/waybar/style.css
rm -rf $HOME/.config/wofi/style.css
rm -rf $HOME/.config/mako/config

cp $HOME/.config/wofi/temas/obscuro.css $HOME/.config/wofi/style.css
cp $HOME/.config/waybar/temas/obscuro.css $HOME/.config/waybar/style.css
cp $HOME/.config/mako/temas/obscuro $HOME/.config/mako/config

#sed -i "s/claro/obscuro/g" $HOME/.config/kitty/kitty.conf
#sed -i "s/gris/obscuro/g" $HOME/.config/kitty/kitty.conf

#sed -i "s/color=ffffff 505050/color=000000 dddddd/g" $HOME/.config/foot/foot.ini
#sed -i "s/foreground=505050/foreground=dddddd/g" $HOME/.config/foot/foot.ini
#sed -i "s/background=ffffff/background=000000/g" $HOME/.config/foot/foot.ini
#sed -i "s/background=242424/background=000000/g" $HOME/.config/foot/foot.ini

rm -rf ${HOME}/.config/gtk-2.0
rm -rf ${HOME}/.config/gtk-3.0
rm -rf ${HOME}/.config/gtk-4.0

cp -R $HOME/.themes/Colloid-Dark/gtk-2.0 ${HOME}/.config/gtk-2.0
cp -R $HOME/.themes/Colloid-Dark/gtk-3.0 ${HOME}/.config/gtk-3.0
cp -R $HOME/.themes/Colloid-Dark/gtk-4.0 ${HOME}/.config/gtk-4.0

pkill -9 mako
mako &
pkill -9 waybar
waybar &
swaybg -i $HOME/.config/wall/obscuro.*
